<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CodexTPSTray</RootNamespace>
    <AssemblyName>CodexTPSTray</AssemblyName>
    <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodexTPSCore\CodexTPSCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="../../../Resources/AppIcon.png">
      <Link>Resources/AppIcon.png</Link>
    </Resource>
  </ItemGroup>

</Project>
